In [7]:
import os.path

PREDS_FILENAME = 'generated_preds.csv'
TRUE_FILENAME = 'generated_true.csv'

# Inspection config
START_FROM_IDX = 2200  # what index to start inspecting from?
EXPLORE_BLOOD_VESSEL = 33


In [8]:
# List of models to inspect
# !!! ADD HERE MORE MODELS !!!
models = dict(  # model-name -> model's absolute path
    CONTROL = r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\mean_baseline\2022-06-03_18-05-19\0',
    DEEP_EHRF = r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\ehrf_tuning_v1\2022-05-27_15-04-53\0',
    CNN = r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\convnn_v1\2022-05-27_14-50-15\0',
    CNN_KILLA = r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\convnn_v1\2022-05-27_16-34-06\0',
    LSTM = r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\lstm_v1\2022-05-28_13-13-05\0',
)

In [9]:
# Utils
from src.baseline.results_summarizer import ResultsSummarizer
import numpy as np
import os

def _load(model_dir):
    y = np.loadtxt(os.path.join(model_dir, TRUE_FILENAME))
    y_pred = np.loadtxt(os.path.join(model_dir, PREDS_FILENAME))
    return y, y_pred

def _inspect(y, y_pred):
    resSum = ResultsSummarizer(None, None, None, y, None, None, y_pred, None, None)
    resSum.describe()
    mse_list = resSum.plot_mse_per_vessel()
    resSum.plot_vascular_pred([EXPLORE_BLOOD_VESSEL])
    return mse_list

In [10]:
for model_name, model_path in models.items():
    print(f">>> Inspecting: {model_name} Model <<<")
    y, y_pred = _load(model_dir=model_path)
    mse_list_control = _inspect(y[START_FROM_IDX:], y_pred[START_FROM_IDX:])
    print(mse_list_control.argsort()[:5])

>>> Inspecting: CONTROL Model <<<
>> Training: MSE=11.966398319429183, R^2=-0.047471831376489665, MAE=2.563361862165601


Average of NRMSE 0.13997766016384158


[11 30 33 21 60]
>>> Inspecting: DEEP_EHRF Model <<<
>> Training: MSE=11.961628215309007, R^2=-0.07389722384837286, MAE=2.556989230275947


Average of NRMSE 0.1410013364246309


[11 30 33 21 60]
>>> Inspecting: CNN Model <<<
>> Training: MSE=11.844622776478975, R^2=-0.036743488514219956, MAE=2.5478577910993825


Average of NRMSE 0.13941410600321125


[11 30 33 21 60]
>>> Inspecting: CNN_KILLA Model <<<
>> Training: MSE=11.575715267039328, R^2=-0.03463556045493879, MAE=2.5348038188665867


Average of NRMSE 0.13811040268842276


[11 30 21 33 60]
>>> Inspecting: LSTM Model <<<
>> Training: MSE=11.613345894273808, R^2=-0.03995311344011006, MAE=2.5402795751981095


Average of NRMSE 0.13839160526182945


[11 30 21 33 60]


In [11]:
# TARGET CNN KILLA
y, y_pred = _load(model_dir=r'C:\Users\MatanBT\My Drive\University\Year 3\Semester B\ML-Workshop\neurovascular-project\logs\experiments\multiruns\convnn_v1\2022-05-27_17-38-36\0')
y, y_pred = np.expand_dims(y, axis=0).T, np.expand_dims(y_pred, axis=0).T
resSum = ResultsSummarizer(None, None, None, y, None, None, y_pred, None, None)
resSum.describe()
# mse_list = resSum.plot_mse_per_vessel()
resSum.plot_vascular_pred([0])
abs(y - y_pred).mean()

>> Training: MSE=73.31482700610859, R^2=-0.2724779853068664, MAE=6.757263801811677


6.757263801811677

In [12]:
(mse_list_cnn[:] - mse_list_control[:]).argsort()

NameError: name 'mse_list_cnn' is not defined

In [ ]:
mse_list_cnn[112] - mse_list_control[112]

In [ ]:
31+45

In [ ]:
12+18